spring.application.name=transactionDemo

spring.datasource.url=jdbc:mysql://localhost:3306/account_db
spring.datasource.username=root
spring.datasource.password=Ritesh@8219

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true