spring.application.name=springJDBCDemo

spring.datasource.url=jdbc:mysql://localhost:3306/student_db
spring.datasource.username=root
spring.datasource.password=Ritesh@8219

#spring.datasource.hikari.

#String url = "jdbc:mysql://localhost:3306/student_db";
#String username = "root";
#String password = "Ritesh@8219";
